[package]
name = "polyglot"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
siderite.workspace = true
siderite-cli = { workspace = true, features = ["postgres"] }
siderite-migrations.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
siderite-testkit.workspace = true
http.workspace = true
