[package]
name = "siderite-core"
description = "App, routing, extractors, responses and errors for siderite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
siderite-openapi.workspace = true
siderite-orm.workspace = true
siderite-validation.workspace = true
base64.workspace = true
bytes.workspace = true
cookie.workspace = true
futures-util.workspace = true
serde_urlencoded.workspace = true
tower-http.workspace = true
uuid.workspace = true
axum.workspace = true
http.workspace = true
http-body-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true

[dev-dependencies]
siderite-validation.workspace = true
jsonschema.workspace = true
siderite-testkit.workspace = true
