[workspace]
resolver = "3"
members = ["crates/*", "examples/hello_world", "examples/todo_sqlite"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jraavis/axumapi"
authors = ["jraavis"]

[workspace.dependencies]
axumapi = { path = "crates/axumapi" }
axumapi-core = { path = "crates/axumapi-core" }
axumapi-macros = { path = "crates/axumapi-macros" }
axumapi-validation = { path = "crates/axumapi-validation" }
axumapi-orm = { path = "crates/axumapi-orm" }
axumapi-backends = { path = "crates/axumapi-backends" }
axumapi-migrations = { path = "crates/axumapi-migrations" }
axumapi-openapi = { path = "crates/axumapi-openapi" }
axumapi-testkit = { path = "crates/axumapi-testkit" }

async-trait = "0.1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "serde"] }
cookie = { version = "0.18", features = ["percent-encode"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "sink"] }
jsonschema = { version = "0.58", default-features = false }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
tower-http = { version = "0.6", features = ["cors", "compression-gzip", "compression-br", "request-id", "trace", "timeout", "fs", "limit", "set-header", "util", "normalize-path"] }
trybuild = "1"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
axum = { version = "0.8", default-features = false, features = ["http1", "http2", "json", "query", "form", "multipart", "ws", "tokio", "matched-path", "original-uri"] }
http = "1"
http-body-util = "0.1"
hyper = "1"
regex = "1"
rust_decimal = { version = "1", default-features = false, features = ["std", "serde-str"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_path_to_error = "0.1"
serde_urlencoded = "0.7"
mongodb = { version = "3.9", default-features = false, features = ["compat-3-0-0", "rustls-tls", "dns-resolver"] }
redis = { version = "1.7", default-features = false, features = ["aio", "tokio-comp", "connection-manager"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "macros", "chrono", "uuid", "rust_decimal", "json"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.5", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
