//! `axumapi-orm`: backend-neutral ORM core.
//!
//! * [`Model`] / [`ModelMeta`]: models and their static metadata, generated by
//!   `#[derive(Model)]`.
//! * [`QuerySet`]: lazy, immutable queries compiled into a [`QueryPlan`].
//! * [`Expr`] / [`Field`]: the typed expression DSL (Django `Q`, `F`, lookups).
//! * [`WritePlan`]: INSERT / UPDATE / DELETE.
//! * [`Db`]: the handle application code uses (pool or transaction).
//! * [`Executor`] / [`Backend`] / [`Transaction`]: implemented by adapters in
//!   `axumapi-backends`; plans are checked against [`BackendCapabilities`]
//!   before any I/O.
//!
//! This crate has **no HTTP dependencies**; the HTTP layer converts
//! [`OrmError`] into API errors.
#![forbid(unsafe_code)]

pub mod backend;
pub mod capabilities;
pub mod db;
pub mod decode;
pub mod error;
pub mod expr;
mod m2m;
pub mod model;
pub mod ops;
mod persist;
pub mod plan;
pub mod queryset;
pub mod relations;
pub mod types;
pub mod value;
pub mod write;

pub use backend::{Backend, ExecResult, Executor, QueryResult, Row, Transaction};
pub use capabilities::{
    BackendCapabilities, BackendKind, Feature, IsolationLevel, RowLocking, TransactionSupport,
};
pub use db::{Databases, Db};
pub use decode::FromValues;
pub use error::{BackendCapabilityError, BackendError, OrmError, QueryError};
pub use expr::functions;
pub use expr::{
    AggFunc, Aggregate, ArrayAgg, Avg, BinaryOp, Calc, CaseBuilder, Column, Count, CumeDist,
    DateLike, DatePart, DenseRank, Expr, Field, FirstValue, FkSlot, Function, Joined, Lag,
    LastValue, Lead, Literal, Lookup, Max, Min, Ntile, Numeric, Operand, PercentRank, Rank, RelHop,
    Related, RelatedColumn, RowNumber, StdDev, StringAgg, Sum, TextLike, TimeLike, UnaryOp,
    Variance, Window, WindowFunc,
};
pub use model::{
    ConstraintMeta, DbDefault, FieldMeta, IndexMeta, ManyToManyMeta, MetaRef, Model, ModelMeta,
    OnDelete, RelationKind, RelationMeta, read_column,
};
pub use ops::ModelOps;
pub use plan::{
    Compound, DistinctMode, JoinExpr, JoinKind, LockMode, OrderDirection, OrderExpr, QueryPlan,
    QuerySource, SelectExpr, SetOp,
};
pub use queryset::{Page, Prefetch, QuerySet, Relation};
pub use relations::{ForeignKey, ManyToManyManager, OneToOne};
pub use types::{DbType, SqlType};
pub use value::Value;
pub use write::{DeletePlan, InsertPlan, UpdatePlan, WritePlan};
