//! `axumapi-orm`: backend-neutral ORM core.
//!
//! * [`Model`] / [`ModelMeta`]: models and their static metadata, generated by
//!   `#[derive(Model)]`.
//! * [`QuerySet`]: lazy, immutable queries compiled into a [`QueryPlan`].
//! * [`Expr`] / [`Field`]: the typed expression DSL (Django `Q`, `F`, lookups).
//! * [`WritePlan`]: INSERT / UPDATE / DELETE.
//! * [`Db`]: the handle application code uses (pool or transaction).
//! * [`Executor`] / [`Backend`] / [`Transaction`]: implemented by adapters in
//!   `axumapi-backends`; plans are checked against [`BackendCapabilities`]
//!   before any I/O.
//!
//! This crate has **no HTTP dependencies**; the HTTP layer converts
//! [`OrmError`] into API errors.
#![forbid(unsafe_code)]

pub mod backend;
pub mod capabilities;
pub mod db;
pub mod error;
pub mod expr;
pub mod model;
pub mod ops;
mod persist;
pub mod plan;
pub mod queryset;
pub mod relations;
pub mod types;
pub mod value;
pub mod write;

pub use backend::{Backend, ExecResult, Executor, QueryResult, Row, Transaction};
pub use capabilities::{
    BackendCapabilities, BackendKind, Feature, IsolationLevel, RowLocking, TransactionSupport,
};
pub use db::{Databases, Db};
pub use error::{BackendCapabilityError, BackendError, OrmError, QueryError};
pub use expr::{BinaryOp, Column, Expr, Field, Lookup, Operand, UnaryOp};
pub use model::{
    ConstraintMeta, DbDefault, FieldMeta, IndexMeta, ManyToManyMeta, MetaRef, Model, ModelMeta,
    OnDelete, RelationKind, RelationMeta, read_column,
};
pub use ops::ModelOps;
pub use plan::{
    DistinctMode, JoinExpr, JoinKind, LockMode, OrderDirection, OrderExpr, QueryPlan, QuerySource,
    SelectExpr,
};
pub use queryset::QuerySet;
pub use relations::{ForeignKey, ManyToManyManager, OneToOne};
pub use types::{DbType, SqlType};
pub use value::Value;
pub use write::{DeletePlan, InsertPlan, UpdatePlan, WritePlan};
