//! The [`Model`] trait and its static [`ModelMeta`].
//!
//! `#[derive(Model)]` generates everything here; the ORM, the migration
//! autodetector and the query compiler read the same `&'static` metadata, so
//! there is one source of truth and no runtime registration.

use crate::backend::Row;
use crate::db::Db;
use crate::error::QueryError;
use crate::plan::OrderDirection;
use crate::queryset::QuerySet;
use crate::types::{DbType, SqlType};
use crate::value::Value;

/// What happens to rows referencing a deleted row (Django `on_delete`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum OnDelete {
    /// Delete referencing rows too.
    #[default]
    Cascade,
    /// Refuse the delete while references exist.
    Protect,
    /// Set the reference to `NULL` (field must be nullable).
    SetNull,
    /// Set the reference to the column default.
    SetDefault,
    /// Leave referencing rows untouched (the database may still enforce).
    DoNothing,
}

/// Kind of a column-backed relation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelationKind {
    /// Many-to-one.
    ForeignKey,
    /// One-to-one (a unique foreign key).
    OneToOne,
}

/// Lazily resolved metadata of another model.
///
/// A function pointer (not a `&'static ModelMeta`) so that models may
/// reference each other in cycles without const-evaluation loops.
pub type MetaRef = fn() -> &'static ModelMeta;

/// Relation carried by a foreign-key column.
#[derive(Debug, Clone, Copy)]
pub struct RelationMeta {
    /// FK or one-to-one.
    pub kind: RelationKind,
    /// Referenced model.
    pub target: MetaRef,
    /// Deletion policy.
    pub on_delete: OnDelete,
    /// Reverse accessor name on the target (`posts`), if any.
    pub related_name: Option<&'static str>,
}

/// A server-side column default (used by migrations and inserts).
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DbDefault {
    /// Current timestamp at insert time (`auto_now_add`).
    Now,
    /// A literal SQL-neutral value.
    Int(i64),
    /// A literal boolean.
    Bool(bool),
    /// A literal string.
    Text(&'static str),
}

/// Static metadata of one concrete column.
#[derive(Debug, Clone, Copy)]
pub struct FieldMeta {
    /// Rust field name.
    pub name: &'static str,
    /// Column name (`author_id` for a `ForeignKey` field named `author`).
    pub column: &'static str,
    /// Column type family.
    pub sql_type: SqlType,
    /// Accepts `NULL`.
    pub nullable: bool,
    /// Part of the primary key.
    pub primary_key: bool,
    /// Value generated by the database (autoincrement / identity).
    pub auto: bool,
    /// `UNIQUE`.
    pub unique: bool,
    /// Single-column index.
    pub index: bool,
    /// `VARCHAR(n)`.
    pub max_length: Option<u32>,
    /// Decimal precision.
    pub max_digits: Option<u32>,
    /// Decimal scale.
    pub decimal_places: Option<u32>,
    /// Database default.
    pub default: Option<DbDefault>,
    /// Refresh to "now" on every save (`auto_now`).
    pub auto_now: bool,
    /// Foreign-key relation.
    pub relation: Option<RelationMeta>,
}

impl FieldMeta {
    /// A plain non-null column of `sql_type`; the derive overrides the rest.
    pub const fn new(name: &'static str, column: &'static str, sql_type: SqlType) -> Self {
        Self {
            name,
            column,
            sql_type,
            nullable: false,
            primary_key: false,
            auto: false,
            unique: false,
            index: false,
            max_length: None,
            max_digits: None,
            decimal_places: None,
            default: None,
            auto_now: false,
            relation: None,
        }
    }
}

/// A many-to-many relation stored in a join table.
#[derive(Debug, Clone, Copy)]
pub struct ManyToManyMeta {
    /// Rust field name on the declaring model.
    pub name: &'static str,
    /// Target model.
    pub target: MetaRef,
    /// Join table (`post_tags` by default, or the explicit through model's table).
    pub through_table: &'static str,
    /// Join-table column pointing at the declaring model.
    pub source_column: &'static str,
    /// Join-table column pointing at the target model.
    pub target_column: &'static str,
    /// Explicit through model, if declared; `None` means an auto-created table.
    pub through: Option<MetaRef>,
    /// Reverse accessor name on the target, if any.
    pub related_name: Option<&'static str>,
}

/// A named multi-column index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IndexMeta {
    /// Index name.
    pub name: &'static str,
    /// Columns in order.
    pub columns: &'static [&'static str],
    /// `UNIQUE` index.
    pub unique: bool,
}

/// A table-level constraint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConstraintMeta {
    /// `UNIQUE (a, b)`.
    Unique {
        /// Constraint name.
        name: &'static str,
        /// Columns.
        columns: &'static [&'static str],
    },
    /// `CHECK (<sql>)`. The SQL is written by the model author, not user input.
    Check {
        /// Constraint name.
        name: &'static str,
        /// Boolean SQL expression.
        sql: &'static str,
    },
}

/// Static metadata of a model (Django `Meta` plus the field list).
#[derive(Debug, Clone, Copy)]
pub struct ModelMeta {
    /// Rust type name (`User`); also the migration model name.
    pub name: &'static str,
    /// Table name.
    pub table: &'static str,
    /// Concrete columns in declaration order.
    pub fields: &'static [FieldMeta],
    /// Many-to-many relations (not columns).
    pub many_to_many: &'static [ManyToManyMeta],
    /// Default ordering as `(column, direction)`.
    pub ordering: &'static [(&'static str, OrderDirection)],
    /// Named indexes.
    pub indexes: &'static [IndexMeta],
    /// Table constraints.
    pub constraints: &'static [ConstraintMeta],
    /// Whether migrations manage this table (`false` for unmanaged tables/views).
    pub managed: bool,
}

impl ModelMeta {
    /// The primary-key column.
    ///
    /// The derive rejects models without exactly one primary key, so this is
    /// only `None` for hand-written, invalid metadata.
    pub fn pk(&self) -> Option<&'static FieldMeta> {
        self.fields.iter().find(|f| f.primary_key)
    }

    /// Field by Rust name.
    pub fn field(&self, name: &str) -> Option<&'static FieldMeta> {
        self.fields.iter().find(|f| f.name == name)
    }

    /// Field by column name.
    pub fn column(&self, column: &str) -> Option<&'static FieldMeta> {
        self.fields.iter().find(|f| f.column == column)
    }
}

/// A database-backed model.
///
/// Implemented by `#[derive(Model)]`. Hand-written implementations must keep
/// [`to_values`](Self::to_values) and [`from_row`](Self::from_row) consistent
/// with [`META`](Self::META).
pub trait Model: Sized + Send + Sync + 'static {
    /// Primary-key type (`i64`, `Uuid`, ...).
    type Pk: DbType + Clone + PartialEq + std::fmt::Debug;

    /// Static metadata.
    const META: &'static ModelMeta;

    /// The primary-key value.
    fn pk(&self) -> Self::Pk;

    /// Store a primary key generated by the database after an insert.
    ///
    /// # Errors
    /// [`QueryError::Decode`] if `value` does not fit the pk type.
    fn set_pk(&mut self, value: Value) -> Result<(), QueryError>;

    /// Whether `save` must INSERT: true for an auto primary key that still
    /// holds its default (e.g. `0`). Models with a manual key return `false`;
    /// `save` then tries UPDATE and falls back to INSERT.
    fn is_unsaved(&self) -> bool;

    /// Every column in [`ModelMeta::fields`] order, as `(column, value)`.
    fn to_values(&self) -> Vec<(&'static str, Value)>;

    /// Decode a model from `row`.
    ///
    /// Columns are looked up as `prefix + column`: `prefix` is `""` for the
    /// root model and `"author__"` for a model loaded via `select_related`.
    ///
    /// # Errors
    /// [`QueryError::Decode`] naming the missing or mistyped column.
    fn from_row(row: &Row, prefix: &str) -> Result<Self, QueryError>;

    /// Lazy queryset over this model (Django `Model.objects`).
    fn objects(db: &Db) -> QuerySet<Self> {
        QuerySet::new(db)
    }
}

/// Read `prefix + column` from `row`, decoding it as `T`.
///
/// # Errors
/// [`QueryError::Decode`] if the column is missing or has the wrong type.
pub fn read_column<T: DbType>(row: &Row, prefix: &str, column: &str) -> Result<T, QueryError> {
    let key = if prefix.is_empty() {
        std::borrow::Cow::Borrowed(column)
    } else {
        std::borrow::Cow::Owned(format!("{prefix}{column}"))
    };
    let value = row.get(&key).cloned().ok_or_else(|| QueryError::Decode {
        column: key.clone().into_owned(),
        reason: "column missing from result".into(),
    })?;
    crate::types::decode(&key, value)
}
