//! Procedural macros for axumapi.
//!
//! These macros are re-exported by the `axumapi` facade crate; generated code
//! only refers to `::axumapi::...` paths, so depend on `axumapi`, not on this
//! crate directly.
//!
//! * `#[get("/path", ...)]`, `#[post(..)]`, `#[put(..)]`, `#[patch(..)]`,
//!   `#[delete(..)]`, `#[head(..)]`, `#[options(..)]`, `#[ws(..)]`: attach a
//!   route (and its OpenAPI metadata) to an `async fn` handler.
//! * `routes![a, module::b]`: collect the routes generated by those attributes.
//! * `#[derive(Schema)]`: JSON Schema / OpenAPI schema generation compatible
//!   with the common `serde` attributes.
#![forbid(unsafe_code)]

mod diag;
mod docs;
mod meta;
mod route;
mod routes;
mod schema;

use proc_macro::TokenStream;

macro_rules! route_macros {
    ($($(#[$doc:meta])* $name:ident => $method:ident),+ $(,)?) => {$(
        $(#[$doc])*
        #[proc_macro_attribute]
        pub fn $name(args: TokenStream, item: TokenStream) -> TokenStream {
            route::expand(route::Method::$method, args.into(), item.into()).into()
        }
    )+};
}

route_macros! {
    /// Route `GET` requests to the annotated `async fn`.
    ///
    /// Syntax: `#[get("/path/{param}", status = 200, tag = "t", tags("a", "b"),
    /// summary = "..", description = "..", operation_id = "..",
    /// response_model = Type, deprecated, hidden)]`.
    get => Get,
    /// Route `POST` requests to the annotated `async fn`. See [`macro@get`].
    post => Post,
    /// Route `PUT` requests to the annotated `async fn`. See [`macro@get`].
    put => Put,
    /// Route `PATCH` requests to the annotated `async fn`. See [`macro@get`].
    patch => Patch,
    /// Route `DELETE` requests to the annotated `async fn`. See [`macro@get`].
    delete => Delete,
    /// Route `HEAD` requests to the annotated `async fn`. See [`macro@get`].
    head => Head,
    /// Route `OPTIONS` requests to the annotated `async fn`. See [`macro@get`].
    options => Options,
    /// Route a WebSocket upgrade (a `GET` request) to the annotated `async fn`.
    /// See [`macro@get`].
    ws => Ws,
}

/// Collect the routes of handlers annotated with the route attributes.
///
/// `routes![create_user, users::list]` expands to
/// `::std::vec![__axumapi_route_create_user(), users::__axumapi_route_list()]`
/// (only the last path segment is rewritten), suitable for `App::routes`.
#[proc_macro]
pub fn routes(input: TokenStream) -> TokenStream {
    routes::expand(input.into()).into()
}

/// Derive `axumapi::validation::Schema` (JSON Schema / OpenAPI 3.1).
///
/// Helper attributes: `#[schema(name = "..", inline)]`,
/// `#[field(min_length = .., ...)]` and the compatible subset of
/// `#[serde(...)]`.
#[proc_macro_derive(Schema, attributes(schema, field, serde))]
pub fn derive_schema(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    match schema::derive(&input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.into_compile_error().into(),
    }
}
