//! DDL snapshots for PostgreSQL and SQLite, including SQLite table-rebuild.
#![allow(clippy::unwrap_used)]

mod common;

use axumapi_migrations::operation::Operation;
use axumapi_migrations::schema_editor::{self, quote_ident};
use axumapi_migrations::state::{ConstraintState, FieldState, ProjectState, SqlType};
use axumapi_orm::BackendKind;
use common::{author_meta, book_meta, post_meta, tag_meta};

fn render_initial(kind: BackendKind) -> Vec<String> {
    let to = ProjectState::from_metas(&[author_meta(), book_meta()]);
    let ops = axumapi_migrations::diff(&ProjectState::new(), &to);
    schema_editor::statements(kind, &ProjectState::new(), &ops).unwrap()
}

#[test]
fn sqlite_author_book_snapshot() {
    let sql = render_initial(BackendKind::Sqlite).join(";\n");
    assert!(
        sql.contains("CREATE TABLE \"authors\" (\n  \"id\" INTEGER PRIMARY KEY AUTOINCREMENT,\n  \"name\" VARCHAR(100) NOT NULL\n)")
    );
    assert!(sql.contains(
        "\"author_id\" BIGINT NOT NULL REFERENCES \"authors\" (\"id\") ON DELETE CASCADE"
    ));
    assert!(sql.contains("\"pages\" INTEGER"));
    assert!(!sql.contains("\"pages\" INTEGER NOT NULL"));
    assert!(sql.contains("CREATE INDEX \"books_author_id_idx\" ON \"books\" (\"author_id\")"));
}

#[test]
fn postgres_author_book_snapshot() {
    let sql = render_initial(BackendKind::Postgres).join(";\n");
    assert!(sql.contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
    assert!(sql.contains("\"name\" VARCHAR(100) NOT NULL"));
    assert!(sql.contains(
        "\"author_id\" BIGINT NOT NULL REFERENCES \"authors\" (\"id\") ON DELETE CASCADE"
    ));
    assert!(sql.contains("CREATE INDEX \"books_author_id_idx\" ON \"books\" (\"author_id\")"));
}

#[test]
fn postgres_types_and_now_default() {
    let to = ProjectState::from_metas(&[post_meta(), tag_meta()]);
    let ops = axumapi_migrations::diff(&ProjectState::new(), &to);
    let sql = schema_editor::statements(BackendKind::Postgres, &ProjectState::new(), &ops)
        .unwrap()
        .join(";\n");
    assert!(sql.contains("\"created_at\" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"));
    assert!(sql.contains("CONSTRAINT \"title_not_empty\" CHECK (length(title) > 0)"));
    assert!(sql.contains("CREATE INDEX \"post_title_idx\" ON \"posts\" (\"title\")"));
    assert!(sql.contains("jsonb") || !sql.contains("Json")); // no json field here
    assert!(sql.contains("ON DELETE CASCADE"));
}

#[test]
fn sqlite_now_default_is_strftime() {
    let to = ProjectState::from_metas(&[post_meta(), tag_meta()]);
    let ops = axumapi_migrations::diff(&ProjectState::new(), &to);
    let sql = schema_editor::statements(BackendKind::Sqlite, &ProjectState::new(), &ops)
        .unwrap()
        .join(";\n");
    assert!(sql.contains("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"));
    let value = axumapi_orm::Value::Text("2026-09-29T12:34:56.123Z".into());
    axumapi_orm::types::decode::<chrono::DateTime<chrono::Utc>>("ts", value).unwrap();
}

#[test]
fn sqlite_remove_field_rebuilds_table() {
    let state = ProjectState::from_metas(&[author_meta(), book_meta()]);
    let op = Operation::RemoveField {
        model: "Book".into(),
        name: "pages".into(),
    };
    let sql = schema_editor::render(BackendKind::Sqlite, &op, &state)
        .unwrap()
        .join(";\n");
    assert!(sql.contains("PRAGMA foreign_keys = OFF"));
    assert!(sql.contains("CREATE TABLE \"books__axumapi_new\""));
    assert!(sql.contains("INSERT INTO \"books__axumapi_new\""));
    assert!(sql.contains("DROP TABLE \"books\""));
    assert!(sql.contains("ALTER TABLE \"books__axumapi_new\" RENAME TO \"books\""));
    assert!(sql.contains("PRAGMA foreign_keys = ON"));
    assert!(!sql.contains("\"pages\""), "{sql}");
}

#[test]
fn sqlite_alter_field_rebuilds() {
    let state = ProjectState::from_metas(&[author_meta()]);
    let mut field = state
        .model("Author")
        .unwrap()
        .field("name")
        .unwrap()
        .clone();
    field.max_length = Some(200);
    let op = Operation::AlterField {
        model: "Author".into(),
        name: "name".into(),
        field,
    };
    let sql = schema_editor::render(BackendKind::Sqlite, &op, &state)
        .unwrap()
        .join(";\n");
    assert!(sql.contains("CREATE TABLE \"authors__axumapi_new\""));
    assert!(sql.contains("VARCHAR(200)"));
}

#[test]
fn sqlite_add_constraint_rebuilds() {
    let state = ProjectState::from_metas(&[author_meta()]);
    let op = Operation::AddConstraint {
        model: "Author".into(),
        constraint: ConstraintState::Check {
            name: "name_present".into(),
            sql: "length(name) > 0".into(),
        },
    };
    let sql = schema_editor::render(BackendKind::Sqlite, &op, &state).unwrap();
    assert!(sql.iter().any(|s| s.contains("authors__axumapi_new")));
    assert!(
        sql.iter()
            .any(|s| s.contains("CONSTRAINT \"name_present\""))
    );
}

#[test]
fn postgres_alter_is_in_place() {
    let state = ProjectState::from_metas(&[author_meta()]);
    let mut field = state
        .model("Author")
        .unwrap()
        .field("name")
        .unwrap()
        .clone();
    field.nullable = true;
    let op = Operation::AlterField {
        model: "Author".into(),
        name: "name".into(),
        field,
    };
    let sql = schema_editor::render(BackendKind::Postgres, &op, &state).unwrap();
    assert_eq!(
        sql,
        vec!["ALTER TABLE \"authors\" ALTER COLUMN \"name\" DROP NOT NULL".to_owned()]
    );
}

#[test]
fn quote_doubles_embedded_quotes() {
    assert_eq!(quote_ident("weird\"name"), "\"weird\"\"name\"");
}

#[test]
fn add_field_sqlite_uses_alter_table() {
    let state = ProjectState::from_metas(&[author_meta()]);
    let op = Operation::AddField {
        model: "Author".into(),
        field: FieldState {
            nullable: true,
            ..FieldState::new("bio", "bio", SqlType::Text)
        },
    };
    let sql = schema_editor::render(BackendKind::Sqlite, &op, &state).unwrap();
    assert_eq!(
        sql,
        vec!["ALTER TABLE \"authors\" ADD COLUMN \"bio\" TEXT".to_owned()]
    );
}

#[test]
fn mysql_is_rejected_before_io() {
    let err = schema_editor::statements(
        BackendKind::MySql,
        &ProjectState::new(),
        &[Operation::RunSQL {
            sql: "SELECT 1".into(),
            reverse_sql: None,
        }],
    )
    .unwrap_err();
    assert!(matches!(
        err,
        axumapi_migrations::MigrationError::UnsupportedBackend(BackendKind::MySql)
    ));
}
