[package]
name = "axumapi-cli"
description = "The axumapi command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
axumapi-backends = { workspace = true, features = ["sqlite"] }
axumapi-config.workspace = true
axumapi-core.workspace = true
axumapi-migrations.workspace = true
axumapi-orm.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[features]
default = []
postgres = ["axumapi-backends/postgres"]
mysql = ["axumapi-backends/mysql"]

[[bin]]
name = "axumapi"
path = "src/main.rs"
doc = false

[dev-dependencies]
serde_json.workspace = true
