[package]
name = "siderite-macros"
description = "Procedural macros for siderite: route attributes, routes![] and derive(Schema)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
regex.workspace = true

[lib]
proc-macro = true
